version: '3.8'

services:
  calculatorapi:
    image: calculatorapi:latest
    ports:
      - "8080:80"  # Map host's port 8080 to container's port 80
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure